# Anime Recommender System:

In [1]:
import numpy as np
import pandas as pd

In [2]:
Animes = pd.read_csv('anime.csv')
Ratings = pd.read_csv('rating.csv')

In [3]:
Animes.head()

anime_id                              name  \
0     32281                    Kimi no Na wa.   
1      5114  Fullmetal Alchemist: Brotherhood   
2     28977                          Gintama°   
3      9253                       Steins;Gate   
4      9969                     Gintama&#039;   

                                               genre   type episodes  rating  \
0               Drama, Romance, School, Supernatural  Movie        1    9.37   
1  Action, Adventure, Drama, Fantasy, Magic, Mili...     TV       64    9.26   
2  Action, Comedy, Historical, Parody, Samurai, S...     TV       51    9.25   
3                                   Sci-Fi, Thriller     TV       24    9.17   
4  Action, Comedy, Historical, Parody, Samurai, S...     TV       51    9.16   

   members  
0   200630  
1   793665  
2   114262  
3   673572  
4   151266

In [4]:
Animes.tail()

anime_id                                               name   genre  \
12289      9316       Toushindai My Lover: Minami tai Mecha-Minami  Hentai   
12290      5543                                        Under World  Hentai   
12291      5621                     Violence Gekiga David no Hoshi  Hentai   
12292      6133  Violence Gekiga Shin David no Hoshi: Inma Dens...  Hentai   
12293     26081                   Yasuji no Pornorama: Yacchimae!!  Hentai   

        type episodes  rating  members  
12289    OVA        1    4.15      211  
12290    OVA        1    4.28      183  
12291    OVA        4    4.88      219  
12292    OVA        1    4.98      175  
12293  Movie        1    5.46      142

In [5]:
Ratings.head()

user_id  anime_id  rating
0        1        20      -1
1        1        24      -1
2        1        79      -1
3        1       226      -1
4        1       241      -1

In [6]:
Ratings.tail()

user_id  anime_id  rating
7813732    73515     16512       7
7813733    73515     17187       9
7813734    73515     22145      10
7813735    73516       790       9
7813736    73516      8074       9

In [7]:
anime = Animes.merge(Ratings, on = 'anime_id')

In [8]:
anime.head()

anime_id            name                                 genre   type  \
0     32281  Kimi no Na wa.  Drama, Romance, School, Supernatural  Movie   
1     32281  Kimi no Na wa.  Drama, Romance, School, Supernatural  Movie   
2     32281  Kimi no Na wa.  Drama, Romance, School, Supernatural  Movie   
3     32281  Kimi no Na wa.  Drama, Romance, School, Supernatural  Movie   
4     32281  Kimi no Na wa.  Drama, Romance, School, Supernatural  Movie   

  episodes  rating_x  members  user_id  rating_y  
0        1      9.37   200630       99         5  
1        1      9.37   200630      152        10  
2        1      9.37   200630      244        10  
3        1      9.37   200630      271        10  
4        1      9.37   200630      278        -1

In [9]:
Animes.shape

(12294, 7)

In [10]:
Ratings.shape

(7813737, 3)

In [11]:
anime.shape

(7813727, 9)

In [12]:
# no. of columns have to keep
# anime_id, name, genre, type, episodes, rating_x, user_id, rating_y


In [13]:
anime.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 7813727 entries, 0 to 7813726
Data columns (total 9 columns):
 #   Column    Dtype  
---  ------    -----  
 0   anime_id  int64  
 1   name      object 
 2   genre     object 
 3   type      object 
 4   episodes  object 
 5   rating_x  float64
 6   members   int64  
 7   user_id   int64  
 8   rating_y  int64  
dtypes: float64(1), int64(4), object(4)
memory usage: 596.1+ MB


In [14]:
anime = anime[['anime_id', 'name', 'genre', 'type', 'episodes', 'rating_x', 'rating_y']]

In [15]:
anime.head()

anime_id            name                                 genre   type  \
0     32281  Kimi no Na wa.  Drama, Romance, School, Supernatural  Movie   
1     32281  Kimi no Na wa.  Drama, Romance, School, Supernatural  Movie   
2     32281  Kimi no Na wa.  Drama, Romance, School, Supernatural  Movie   
3     32281  Kimi no Na wa.  Drama, Romance, School, Supernatural  Movie   
4     32281  Kimi no Na wa.  Drama, Romance, School, Supernatural  Movie   

  episodes  rating_x  rating_y  
0        1      9.37         5  
1        1      9.37        10  
2        1      9.37        10  
3        1      9.37        10  
4        1      9.37        -1

In [16]:
# to check whether there is any missing value
anime.isnull().sum()

anime_id      0
name          0
genre       110
type          4
episodes      0
rating_x      6
rating_y      0
dtype: int64

In [17]:
anime.dropna(inplace= True)

In [18]:
anime.isnull().sum()

anime_id    0
name        0
genre       0
type        0
episodes    0
rating_x    0
rating_y    0
dtype: int64

In [19]:
anime.duplicated().sum()

7734972

In [20]:
 anime.drop_duplicates(subset='name', keep='first', inplace=True)

In [21]:
anime.duplicated().sum()

0

In [22]:
anime.head()

anime_id                              name  \
0         32281                    Kimi no Na wa.   
2199       5114  Fullmetal Alchemist: Brotherhood   
26773     28977                          Gintama°   
28159      9253                       Steins;Gate   
47442      9969                     Gintama&#039;   

                                                   genre   type episodes  \
0                   Drama, Romance, School, Supernatural  Movie        1   
2199   Action, Adventure, Drama, Fantasy, Magic, Mili...     TV       64   
26773  Action, Comedy, Historical, Parody, Samurai, S...     TV       51   
28159                                   Sci-Fi, Thriller     TV       24   
47442  Action, Comedy, Historical, Parody, Samurai, S...     TV       51   

       rating_x  rating_y  
0          9.37         5  
2199       9.26        10  
26773      9.25        -1  
28159      9.17         9  
47442      9.16         9

In [23]:
anime.iloc[0].genre

'Drama, Romance, School, Supernatural'

In [24]:
anime.head()

anime_id                              name  \
0         32281                    Kimi no Na wa.   
2199       5114  Fullmetal Alchemist: Brotherhood   
26773     28977                          Gintama°   
28159      9253                       Steins;Gate   
47442      9969                     Gintama&#039;   

                                                   genre   type episodes  \
0                   Drama, Romance, School, Supernatural  Movie        1   
2199   Action, Adventure, Drama, Fantasy, Magic, Mili...     TV       64   
26773  Action, Comedy, Historical, Parody, Samurai, S...     TV       51   
28159                                   Sci-Fi, Thriller     TV       24   
47442  Action, Comedy, Historical, Parody, Samurai, S...     TV       51   

       rating_x  rating_y  
0          9.37         5  
2199       9.26        10  
26773      9.25        -1  
28159      9.17         9  
47442      9.16         9

In [25]:
anime.head()

anime_id                              name  \
0         32281                    Kimi no Na wa.   
2199       5114  Fullmetal Alchemist: Brotherhood   
26773     28977                          Gintama°   
28159      9253                       Steins;Gate   
47442      9969                     Gintama&#039;   

                                                   genre   type episodes  \
0                   Drama, Romance, School, Supernatural  Movie        1   
2199   Action, Adventure, Drama, Fantasy, Magic, Mili...     TV       64   
26773  Action, Comedy, Historical, Parody, Samurai, S...     TV       51   
28159                                   Sci-Fi, Thriller     TV       24   
47442  Action, Comedy, Historical, Parody, Samurai, S...     TV       51   

       rating_x  rating_y  
0          9.37         5  
2199       9.26        10  
26773      9.25        -1  
28159      9.17         9  
47442      9.16         9

In [30]:
anime['genre']=anime['genre'].apply(Convert7)

In [27]:
def Convert7(string):
    li = list(string.split(" "))
    return li
  

In [28]:
anime['type']=anime['type'].apply(Convert7)

In [31]:
anime['tags'] = anime['genre'] + anime['type']

In [32]:
anime.head()

anime_id                              name  \
0         32281                    Kimi no Na wa.   
2199       5114  Fullmetal Alchemist: Brotherhood   
26773     28977                          Gintama°   
28159      9253                       Steins;Gate   
47442      9969                     Gintama&#039;   

                                                   genre     type episodes  \
0              [Drama,, Romance,, School,, Supernatural]  [Movie]        1   
2199   [Action,, Adventure,, Drama,, Fantasy,, Magic,...     [TV]       64   
26773  [Action,, Comedy,, Historical,, Parody,, Samur...     [TV]       51   
28159                                [Sci-Fi,, Thriller]     [TV]       24   
47442  [Action,, Comedy,, Historical,, Parody,, Samur...     [TV]       51   

       rating_x  rating_y                                               tags  
0          9.37         5   [Drama,, Romance,, School,, Supernatural, Movie]  
2199       9.26        10  [Action,, Adventure,, Drama,, Fantasy,, Magic,...  
26773      9.25        -1  [Action,, Comedy,, Historical,, Parody,, Samur...  
28159      9.17         9                            [Sci-Fi,, Thriller, TV]  
47442      9.16         9  [Action,, Comedy,, Historical,, Parody,, Samur...

In [33]:
anime.head()

anime_id                              name  \
0         32281                    Kimi no Na wa.   
2199       5114  Fullmetal Alchemist: Brotherhood   
26773     28977                          Gintama°   
28159      9253                       Steins;Gate   
47442      9969                     Gintama&#039;   

                                                   genre     type episodes  \
0              [Drama,, Romance,, School,, Supernatural]  [Movie]        1   
2199   [Action,, Adventure,, Drama,, Fantasy,, Magic,...     [TV]       64   
26773  [Action,, Comedy,, Historical,, Parody,, Samur...     [TV]       51   
28159                                [Sci-Fi,, Thriller]     [TV]       24   
47442  [Action,, Comedy,, Historical,, Parody,, Samur...     [TV]       51   

       rating_x  rating_y                                               tags  
0          9.37         5   [Drama,, Romance,, School,, Supernatural, Movie]  
2199       9.26        10  [Action,, Adventure,, Drama,, Fantasy,, Magic,...  
26773      9.25        -1  [Action,, Comedy,, Historical,, Parody,, Samur...  
28159      9.17         9                            [Sci-Fi,, Thriller, TV]  
47442      9.16         9  [Action,, Comedy,, Historical,, Parody,, Samur...

In [34]:
new_df = anime[['anime_id', 'name', 'tags']]

In [35]:
new_df.head()

anime_id                              name  \
0         32281                    Kimi no Na wa.   
2199       5114  Fullmetal Alchemist: Brotherhood   
26773     28977                          Gintama°   
28159      9253                       Steins;Gate   
47442      9969                     Gintama&#039;   

                                                    tags  
0       [Drama,, Romance,, School,, Supernatural, Movie]  
2199   [Action,, Adventure,, Drama,, Fantasy,, Magic,...  
26773  [Action,, Comedy,, Historical,, Parody,, Samur...  
28159                            [Sci-Fi,, Thriller, TV]  
47442  [Action,, Comedy,, Historical,, Parody,, Samur...

In [36]:
new_df['tags']=new_df['tags'].apply(lambda x:" ".join(x))

<ipython-input-36-53a061086f2e>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags']=new_df['tags'].apply(lambda x:" ".join(x))


In [37]:
new_df.head()

anime_id                              name  \
0         32281                    Kimi no Na wa.   
2199       5114  Fullmetal Alchemist: Brotherhood   
26773     28977                          Gintama°   
28159      9253                       Steins;Gate   
47442      9969                     Gintama&#039;   

                                                    tags  
0             Drama, Romance, School, Supernatural Movie  
2199   Action, Adventure, Drama, Fantasy, Magic, Mili...  
26773  Action, Comedy, Historical, Parody, Samurai, S...  
28159                                Sci-Fi, Thriller TV  
47442  Action, Comedy, Historical, Parody, Samurai, S...

In [38]:
new_df['tags'][0]

'Drama, Romance, School, Supernatural Movie'

In [39]:
new_df['tags']=new_df['tags'].apply(lambda x:x.lower())

<ipython-input-39-242d679aab18>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags']=new_df['tags'].apply(lambda x:x.lower())


In [40]:
new_df.head()

anime_id                              name  \
0         32281                    Kimi no Na wa.   
2199       5114  Fullmetal Alchemist: Brotherhood   
26773     28977                          Gintama°   
28159      9253                       Steins;Gate   
47442      9969                     Gintama&#039;   

                                                    tags  
0             drama, romance, school, supernatural movie  
2199   action, adventure, drama, fantasy, magic, mili...  
26773  action, comedy, historical, parody, samurai, s...  
28159                                sci-fi, thriller tv  
47442  action, comedy, historical, parody, samurai, s...

In [41]:
new_df['tags'][0]

'drama, romance, school, supernatural movie'

In [42]:
new_df.reset_index(inplace = True)

In [43]:
new_df.head()

index  anime_id                              name  \
0      0     32281                    Kimi no Na wa.   
1   2199      5114  Fullmetal Alchemist: Brotherhood   
2  26773     28977                          Gintama°   
3  28159      9253                       Steins;Gate   
4  47442      9969                     Gintama&#039;   

                                                tags  
0         drama, romance, school, supernatural movie  
1  action, adventure, drama, fantasy, magic, mili...  
2  action, comedy, historical, parody, samurai, s...  
3                                sci-fi, thriller tv  
4  action, comedy, historical, parody, samurai, s...

In [44]:
new_df = new_df[['anime_id', 'name', 'tags']]

In [45]:
new_df.head()

anime_id                              name  \
0     32281                    Kimi no Na wa.   
1      5114  Fullmetal Alchemist: Brotherhood   
2     28977                          Gintama°   
3      9253                       Steins;Gate   
4      9969                     Gintama&#039;   

                                                tags  
0         drama, romance, school, supernatural movie  
1  action, adventure, drama, fantasy, magic, mili...  
2  action, comedy, historical, parody, samurai, s...  
3                                sci-fi, thriller tv  
4  action, comedy, historical, parody, samurai, s...

In [46]:
new_df['tags'][1]

'action, adventure, drama, fantasy, magic, military, shounen tv'

In [47]:
new_df.shape

(11161, 3)

In [48]:
new_df.head()

anime_id                              name  \
0     32281                    Kimi no Na wa.   
1      5114  Fullmetal Alchemist: Brotherhood   
2     28977                          Gintama°   
3      9253                       Steins;Gate   
4      9969                     Gintama&#039;   

                                                tags  
0         drama, romance, school, supernatural movie  
1  action, adventure, drama, fantasy, magic, mili...  
2  action, comedy, historical, parody, samurai, s...  
3                                sci-fi, thriller tv  
4  action, comedy, historical, parody, samurai, s...

In [49]:
new_df.rename(columns = {'name':'title'}, inplace = True)

In [50]:
new_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11161 entries, 0 to 11160
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype 
---  ------    --------------  ----- 
 0   anime_id  11161 non-null  int64 
 1   title     11161 non-null  object
 2   tags      11161 non-null  object
dtypes: int64(1), object(2)
memory usage: 261.7+ KB


In [51]:
new_df.isnull().sum()

anime_id    0
title       0
tags        0
dtype: int64

In [52]:
new_df.duplicated().sum()

0

In [53]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features = 5000, stop_words = 'english')

In [54]:
vector=cv.fit_transform(new_df['tags']).toarray()

In [55]:
vector

array([[0, 0, 0, ..., 0, 0, 0],
       [1, 1, 0, ..., 0, 0, 0],
       [1, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [56]:
vector.shape

(11161, 51)

In [57]:
vector[0]

array([0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0], dtype=int64)

In [58]:
cv.get_feature_names()

['action',
 'adventure',
 'ai',
 'arts',
 'cars',
 'comedy',
 'dementia',
 'demons',
 'drama',
 'ecchi',
 'fantasy',
 'fi',
 'game',
 'harem',
 'hentai',
 'historical',
 'horror',
 'josei',
 'kids',
 'life',
 'magic',
 'martial',
 'mecha',
 'military',
 'movie',
 'music',
 'mystery',
 'ona',
 'ova',
 'parody',
 'police',
 'power',
 'psychological',
 'romance',
 'samurai',
 'school',
 'sci',
 'seinen',
 'shoujo',
 'shounen',
 'slice',
 'space',
 'special',
 'sports',
 'super',
 'supernatural',
 'thriller',
 'tv',
 'vampire',
 'yaoi',
 'yuri']

In [59]:
 from sklearn.metrics.pairwise import cosine_similarity

In [60]:
cosine_similarity(vector)

array([[1.        , 0.15811388, 0.        , ..., 0.        , 0.        ,
        0.31622777],
       [0.15811388, 1.        , 0.35355339, ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.35355339, 1.        , ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.        , 0.        , 0.        , ..., 1.        , 1.        ,
        0.5       ],
       [0.        , 0.        , 0.        , ..., 1.        , 1.        ,
        0.5       ],
       [0.31622777, 0.        , 0.        , ..., 0.5       , 0.5       ,
        1.        ]])

In [61]:
cosine_similarity(vector).shape   #it is distance of 1 anime with every other anime

(11161, 11161)

In [62]:
similarity = cosine_similarity(vector)

In [63]:
similarity[0] # first column is 1 cause it is similarity of first anime with first anime

array([1.        , 0.15811388, 0.        , ..., 0.        , 0.        ,
       0.31622777])

In [64]:
similarity[1] # 2nd column is 1 cause it is similarity of 2nd anime with 2nd anime and thats why the diagonal of vector will be 1

array([0.15811388, 1.        , 0.35355339, ..., 0.        , 0.        ,
       0.        ])

In [65]:
# we want to fetch a index of an anime whenever user want to
new_df[new_df['title'] == 'Fullmetal Alchemist: Brotherhood'].index[0]

1

In [66]:
sorted(list(enumerate(similarity[0])), reverse=True , key = lambda x:x[1])[1:6]

[(1089, 0.9128709291752769),
 (202, 0.8944271909999159),
 (1465, 0.8944271909999159),
 (1925, 0.8944271909999159),
 (59, 0.7999999999999999)]

In [67]:
new_df.head()

anime_id                             title  \
0     32281                    Kimi no Na wa.   
1      5114  Fullmetal Alchemist: Brotherhood   
2     28977                          Gintama°   
3      9253                       Steins;Gate   
4      9969                     Gintama&#039;   

                                                tags  
0         drama, romance, school, supernatural movie  
1  action, adventure, drama, fantasy, magic, mili...  
2  action, comedy, historical, parody, samurai, s...  
3                                sci-fi, thriller tv  
4  action, comedy, historical, parody, samurai, s...

In [68]:
def recommend(anime):
    anime_index = new_df[new_df['title'] == anime].index[0]
    distances = similarity[anime_index]
    anime_list = sorted(list(enumerate(distances)), reverse=True , key = lambda x:x[1])[1:6]
    
    for i in anime_list:
        print(new_df.iloc[i[0]].title)
    

# Making Recommendations

In [69]:
# recommedations by giving watched anime user liked
recommend('Fullmetal Alchemist: Brotherhood')

Fullmetal Alchemist
Magi: The Kingdom of Magic
Magi: The Labyrinth of Magic
Magi: Sinbad no Bouken (TV)
Densetsu no Yuusha no Densetsu


In [70]:
new_df.iloc[1]


anime_id                                                 5114
title                        Fullmetal Alchemist: Brotherhood
tags        action, adventure, drama, fantasy, magic, mili...
Name: 1, dtype: object

## To forward data to site:

In [71]:
import pickle


In [72]:
pickle.dump(new_df.to_dict(), open('anime_dict.pkl','wb'))

In [73]:
pickle.dump(similarity, open('similarity.pkl', 'wb'))